neo4j:
  name: neo4j-standalone
  edition: "community"
  acceptLicenseAgreement: "no"
  resources:
    cpu: "1000m"
    memory: "2Gi"
  password: "project2phase2"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 10Gi
env:
  NEO4J_PLUGINS: '["graph-data-science"]'

config:
  dbms.security.procedures.unrestricted: "gds.*"
  server.config.strict_validation.enabled: "false"
  dbms.security.procedures.allowlist: "gds.*"

logInitialPassword: true